---
- hosts: all
  become: yes
  tasks:
    - name: Apt update
      apt:
        upgrade: yes
        update_cache: yes
        state: present
    - name: Install LAMP
      apt:
        name: mysql-server, php, libapache2-mod-php, php-mysql, apache2
        state: present
    - name: Allow Apache
      community.general.ufw:
        name: Apache
        rule: allow
        state: enabled
        port: 80
    - name: Create Virtual Host
      file:
        path: /var/www/domain
        owner: some
        state: directory
    - name: Set domain
      ansible.builtin.template:
        src: ~/ansible-practice/setdomain.j2
        dest: /etc/apache2/sites-available/domain.conf
        backup: yes
    - name: Page html
      ansible.builtin.template:
        src: ~/ansible-practice/pagehtml.j2
        dest: /var/www/domain/index.html
    - name: Sets up PHP info page
      ansible.builtin.template:
        src: ~/ansible-practice/phpinfo.j2
        dest: /var/www/domain/info.php
        backup: yes
    - name: Enable site
      shell: /usr/sbin/a2ensite domain
    - name: Reload apache2
      systemd:
        name: apache2
        state: reloaded
    - name: Restart apache2
      systemd:
        name: apache2
        state: restarted
